easy_admin:
    site_name: "AMS APPS HUB"

    # Configuration des assets personnalisés si nécessaire
    # assets:
    #     css:
    #         - 'css/custom-admin.css'
    #     js:
    #         - 'js/custom-admin.js'
